trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solution1: 'eShop.sln'
  solution2: 'eShop.Web.sln'

steps:
# Checkout code
- checkout: self

# Use latest .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true

# Cache NuGet dependencies to speed up builds
- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | $(Build.SourcesDirectory)/**/*.csproj'
    restoreKeys: |
      nuget | "$(Agent.OS)"
    path: $(NuGetPackageRoot)

# Restore both solutions
- task: DotNetCoreCLI@2
  displayName: 'Restore eShop.sln and eShop.Web.sln'
  inputs:
    command: restore
    projects: |
      $(solution1)
      $(solution2)

# Build both solutions and all API projects
- task: DotNetCoreCLI@2
  displayName: 'Build Solutions and API Projects'
  inputs:
    command: build
    projects: |
      $(solution1)
      $(solution2)
      src/Basket.API/Basket.API.csproj
      src/Catalog.API/Catalog.API.csproj
      src/Identity.API/Identity.API.csproj
      src/Ordering.API/Ordering.API.csproj
      src/Webhooks.API/Webhooks.API.csproj
    arguments: '--configuration $(buildConfiguration) --no-restore'

# Run Unit & Functional Tests
- task: DotNetCoreCLI@2
  displayName: 'Run Unit & Functional Tests'
  inputs:
    command: test
    projects: |
      tests/Basket.UnitTests/Basket.UnitTests.csproj
      tests/Catalog.FunctionalTests/Catalog.FunctionalTests.csproj
      tests/Ordering.FunctionalTests/Ordering.FunctionalTests.csproj
      tests/Ordering.UnitTests/Ordering.UnitTests.csproj
    arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'

# Publish test results
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/TestResults/*.trx'
    testRunTitle: 'Test Results'

# Publish code coverage
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

# Optional: Publish build artifacts
- task: PublishBuildArtifacts@1
  condition: succeeded()
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
    publishLocation: 'Container'